{% set __NAME__ = "pixie" %}
{% set __VERSION_SUFFIX__ = "" %} # debug version suffix, appended to the version
{% set __VERSION__ =  "%s%s" % (environ.get('GIT_DESCRIBE_TAG', ''), __VERSION_SUFFIX__) %}

package:
   name: {{ __NAME__ }}
   version: {{ __VERSION__ }}

source:
   path: ../../..


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .
  string: {{ GIT_BUILD_STR }}
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{__VERSION__}}


requirements:
  host:
    - python
    - setuptools_scm
  build:
    - python
    - llvmlite
  run:
    - python
    - llvmlite

test:
  requires:
    - pytest
    - numpy
    - numba
  commands:
    - pytest --pyargs pixie

about:
  home: https://github.com/numba/pixie
  license: BSD
  license_file: LICENSE
  summary: Creates performance portable libraries with embedded source representations.
