{% set name = "pixie" %}
{% set VERSION_SUFFIX = "" %} # debug version suffix, appended to the version

package:
   name: {{ name }}
   version: {{ "%s%s" % (environ.get('GIT_DESCRIBE_TAG', ''), VERSION_SUFFIX) }}

source:
   path: ../../..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  string: {{ GIT_BUILD_STR }}

requirements:
  # build and run dependencies are duplicated to avoid setuptools issues
  # when we also set install_requires in setup.py
  build:
    - python
    - llvmlite
  run:
    - python
    - llvmlite

test:
  requires:
    - pytest
    - numpy
    - numba

about:
  home: https://github.com/numba/pixie
  license: BSD
  license_file: LICENSE
  summary: Creates performance portable libraries with embedded source representations.
