name: anaconda.org build and upload

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  anaconda_org_build_and_upload:
    name: anaconda.org upload py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          auto-activate-base: false
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install pytest coverage numpy numba conda-build anaconda-client
      - name: Build and upload
        uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
        with:
          meta_yaml_dir: buildscripts/conda_recipes/pixie/
          python-version: ${{ matrix.python-version }}
          overwrite: True
          user: numba
          label: dev
          token: ${{ secrets.ANACONDA_ORG_TOKEN }}
